# Generated by Django 4.0 on 2022-01-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xafari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='amount',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
