# Generated by Django 4.0 on 2022-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xafari', '0002_places_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('from_place', models.TextField(max_length=25)),
                ('to_place', models.TextField(max_length=25)),
                ('number_of_passengers', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('leaving_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='places',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
